import {installIntegrationSettings,loadSavedRazorpay} from './integrations.js';
import {installMessaging,installRechargeWebhook,startMessageWorker} from './messaging.js';
import express from 'express';
import {installPublicCMS,installPlatformCMS} from './cms.js';
import cookieParser from 'cookie-parser';
import helmet from 'helmet';
import { createClient } from '@supabase/supabase-js';
import { z } from 'zod';
import { randomBytes,randomUUID,createHmac,createHash,timingSafeEqual } from 'node:crypto';
import { fields,validateTenantRecord } from './record-validation.js';
import { bookingDuration,bookingsOverlap } from '../shared/booking-duration.js';
import { renderConfirmation } from '../shared/confirmation.js';
import { entitlement,publicPlan,billingMetrics,verifyCheckout,verifyWebhook } from './saas-core.js';
const env=process.env;
for(const key of ['SUPABASE_URL','SUPABASE_ANON_KEY','SUPABASE_SERVICE_ROLE_KEY','APP_URL'])if(!env[key])throw Error(`${key} is required in SaaS mode. Configure deployment secrets; never commit them.`);
const origin=new URL(env.APP_URL).origin,secure=new URL(origin).protocol==='https:';
if(env.NODE_ENV==='production'&&!secure)throw Error('APP_URL must use HTTPS in production.');
if(!/^https:\/\//.test(env.SUPABASE_URL))throw Error('SUPABASE_URL must use HTTPS.');
const options={auth:{persistSession:false,autoRefreshToken:false,detectSessionInUrl:false}};
const admin=createClient(env.SUPABASE_URL,env.SUPABASE_SERVICE_ROLE_KEY,options);
await loadSavedRazorpay(admin,async q=>{const {data,error}=await q;if(error)throw Error('Integration settings unavailable. Apply messaging migration and check the encryption key.');return data;});
const billingEnabled=!!(env.RAZORPAY_KEY_ID&&env.RAZORPAY_KEY_SECRET&&env.RAZORPAY_WEBHOOK_SECRET);
if([env.RAZORPAY_KEY_ID,env.RAZORPAY_KEY_SECRET,env.RAZORPAY_WEBHOOK_SECRET].some(Boolean)&&!billingEnabled)throw Error('Configure all three Razorpay credentials together.');
const billingMode=env.RAZORPAY_KEY_ID?.startsWith('rzp_live_')?'live':'test';
if(billingEnabled&&env.NODE_ENV==='production'&&billingMode==='test'&&env.ALLOW_TEST_BILLING!=='true')throw Error('Test billing requires ALLOW_TEST_BILLING=true in a production Node deployment.');
const authClient=()=>createClient(env.SUPABASE_URL,env.SUPABASE_ANON_KEY,options);
const userClient=token=>createClient(env.SUPABASE_URL,env.SUPABASE_ANON_KEY,{...options,global:{headers:{Authorization:'Bearer '+token}}});
const app=express();app.disable('x-powered-by');app.set('trust proxy',Number(env.TRUST_PROXY||0));
app.use(helmet({contentSecurityPolicy:{directives:{defaultSrc:["'self'"],scriptSrc:["'self'",'https://checkout.razorpay.com','https://*.razorpay.com','https://challenges.cloudflare.com'],styleSrc:["'self'","'unsafe-inline'",'https://fonts.googleapis.com'],fontSrc:["'self'",'https://fonts.gstatic.com'],imgSrc:["'self'",'data:','https://*.razorpay.com'],connectSrc:["'self'",'https://*.razorpay.com','https://challenges.cloudflare.com'],frameSrc:['https://*.razorpay.com','https://challenges.cloudflare.com'],frameAncestors:["'none'"],objectSrc:["'none'"],upgradeInsecureRequests:secure?[]:null}},crossOriginEmbedderPolicy:false}));
const fail=(message,status=400)=>Object.assign(Error(message),{status});
const route=fn=>(req,res,next)=>Promise.resolve(fn(req,res)).catch(next);
const result=async query=>{const {data,error}=await query;if(error)throw fail(error.message);return data;};
const rpc=(name,args)=>result(admin.rpc(name,args));
const accessCookie=secure?'__Host-gh_access':'gh_access',refreshCookie=secure?'__Host-gh_refresh':'gh_refresh';
const cookieOptions={httpOnly:true,secure,sameSite:'lax',path:'/'};
function saveSession(res,s){res.cookie(accessCookie,s.access_token,{...cookieOptions,maxAge:3600000});res.cookie(refreshCookie,s.refresh_token,{...cookieOptions,maxAge:7*86400000});}
function clearSession(res){res.clearCookie(accessCookie,cookieOptions);res.clearCookie(refreshCookie,cookieOptions);}
// Express middleware wrapper for distributed auth/checkout limits.
const rateLimit=(tag,hits,seconds)=>async(req,res,next)=>{try{const key=createHmac('sha256',env.RATE_LIMIT_SECRET||env.SUPABASE_SERVICE_ROLE_KEY).update(tag+'|'+req.ip).digest('hex');if(!await rpc('saas_rate_limit',{bucket:key,max_hits:hits,seconds}))return next(fail('Too many attempts. Please try again later.',429));next();}catch(error){next(error);}};
async function razor(path,method='GET',body){if(!billingEnabled)throw fail('Billing is not configured. Contact the platform operator.',503);const response=await fetch('https://api.razorpay.com/v1/'+path,{method,headers:{Authorization:'Basic '+Buffer.from(env.RAZORPAY_KEY_ID+':'+env.RAZORPAY_KEY_SECRET).toString('base64'),'Content-Type':'application/json'},...(body?{body:JSON.stringify(body)}:{}),signal:AbortSignal.timeout(15000)});const data=await response.json();if(!response.ok)throw fail('Payment provider could not complete this request. Please contact support before retrying.',502);return data;}
async function synchronize(id,eventId=null,eventType='verification',payment=null){const observed=new Date().toISOString();const state=await razor('subscriptions/'+encodeURIComponent(id));const p={status:state.status,current_end:state.current_end||0};if(payment&&eventType==='subscription.charged'&&payment.status==='captured'&&payment.currency==='INR'){p.payment_id=payment.id;p.amount_paise=payment.amount;p.currency=payment.currency;p.captured_at=payment.created_at;}await rpc('saas_sync_subscription',{provider_id:id,observed,p,event_id:eventId,event_type:eventType});return state;}
installRechargeWebhook(app,{admin,result,rpc,route,razor});
// Signature validation needs the original bytes; register before express.json().
app.post('/api/webhooks/razorpay',express.raw({type:'application/json',limit:'256kb'}),route(async(req,res)=>{
 if(!billingEnabled||!Buffer.isBuffer(req.body)||!verifyWebhook(req.body,req.get('x-razorpay-signature'),env.RAZORPAY_WEBHOOK_SECRET))throw fail('Invalid webhook signature.',401);
 const event=JSON.parse(req.body.toString('utf8')),id=event.payload?.subscription?.entity?.id;
 if(!id||!/^sub_[A-Za-z0-9]+$/.test(id)||!String(event.event).startsWith('subscription.'))return res.json({received:true,ignored:true});
 const eventId=req.get('x-razorpay-event-id')||createHash('sha256').update(req.body).digest('hex');
 if(await result(admin.from('billing_events').select('event_id').eq('event_id',eventId).maybeSingle()))return res.json({received:true,duplicate:true});
 // Only IDs created for this application can change entitlements. Unknown IDs return 503 for provider retry/reconciliation.
 if(!await result(admin.from('saas_subscriptions').select('tenant_id').eq('provider_subscription_id',id).maybeSingle()))throw fail('Subscription not registered yet; retry webhook.',503);
 await synchronize(id,eventId,event.event,event.payload?.payment?.entity);res.json({received:true});
}));
app.use(express.json({limit:'256kb'}));app.use(cookieParser());
app.use('/api',(req,res,next)=>{res.set('Cache-Control','no-store');if(!req.cookies.gh_csrf){res.cookie('gh_csrf',randomBytes(24).toString('hex'),{secure,sameSite:'strict',path:'/',maxAge:7*86400000});}if(!['GET','HEAD','OPTIONS'].includes(req.method)){const a=req.cookies.gh_csrf,b=req.get('x-csrf-token');if(req.get('origin')&&req.get('origin')!==origin)return next(fail('Untrusted request origin.',403));if(!a||!b||! /^[a-f0-9]{48}$/.test(a)||! /^[a-f0-9]{48}$/.test(b)||!timingSafeEqual(Buffer.from(a),Buffer.from(b)))return next(fail('Session security check failed. Refresh the page and retry.',403));}next();});
app.get('/healthz',route(async(_req,res)=>{await Promise.all(['saas_plans','cms_entries','platform_integrations','message_jobs'].map(table=>result(admin.from(table).select(table==='platform_integrations'?'kind':'id').limit(1))));res.json({status:'ok',mode:'saas'});}));
app.get('/api/config',(_req,res)=>res.json({mode:'saas',billingEnabled,billingMode,registrationEnabled:env.REGISTRATION_ENABLED!=='false',supportEmail:env.SUPPORT_EMAIL||'',captchaSiteKey:env.TURNSTILE_SITE_KEY||''}));
app.get('/api/public/plans',route(async(_req,res)=>res.json((await result(admin.from('saas_plans').select('*').eq('published',true).order('monthly_paise'))).map(publicPlan))));
app.get('/api/public/halls',rateLimit('public-halls',120,900),route(async(_req,res)=>{const orgs=await result(admin.from('organizations').select('id,name,city').eq('status','active'));const orgById=new Map(orgs.map(o=>[o.id,o]));const halls=[];for(let offset=0;;offset+=1000){const page=await result(admin.from('saas_records').select('id,tenant_id,body').eq('kind','halls').order('id').range(offset,offset+999));for(const row of page){const org=orgById.get(row.tenant_id);const b=row.body||{};if(!org||b.status!=='Available')continue;halls.push({id:row.id,name:b.name||'',type:b.type||'',capacity:b.capacity??0,price:b.price??0,morningPrice:b.morningPrice??null,afternoonPrice:b.afternoonPrice??null,eveningPrice:b.eveningPrice??null,image:b.image||'',description:b.description||'',city:org.city||'',venue:org.name||''});}if(page.length<1000)break;}res.json({halls,cities:[...new Set(halls.map(h=>h.city).filter(Boolean))].sort()});}));
app.get('/api/public/halls/:id',rateLimit('public-halls',120,900),route(async(req,res)=>{const id=z.string().min(1).max(64).parse(req.params.id);const row=await result(admin.from('saas_records').select('id,tenant_id,body').eq('kind','halls').eq('id',id).maybeSingle());if(!row)throw fail('Hall not found.',404);const org=await result(admin.from('organizations').select('id,name,city').eq('status','active').eq('id',row.tenant_id).maybeSingle());if(!org)throw fail('Hall not found.',404);const b=row.body||{};const [addons,plans]=await Promise.all([result(admin.from('saas_records').select('id,body').eq('kind','addons').eq('tenant_id',row.tenant_id).order('id').range(0,999)),result(admin.from('saas_records').select('id,body').eq('kind','plans').eq('tenant_id',row.tenant_id).order('id').range(0,999))]);const active=list=>list.filter(r=>(r.body||{}).status==='Active').map(r=>({...r.body,id:r.id}));res.json({hall:{...b,id:row.id,city:org.city||'',venue:org.name||''},addons:active(addons),plans:active(plans)});}));
installPublicCMS(app,{admin,result,rpc,route,rateLimit});
const credentials=z.object({email:z.string().email().max(254),password:z.string().min(12).max(128),name:z.string().trim().min(1).max(120).optional(),captchaToken:z.string().optional()});
app.post('/api/auth/register',rateLimit('signup',5,900),route(async(req,res)=>{
 if(env.REGISTRATION_ENABLED==='false')throw fail('Registration is currently closed.',403);const p=credentials.extend({name:z.string().trim().min(1).max(120)}).parse(req.body);
 const {error}=await authClient().auth.signUp({email:p.email,password:p.password,options:{data:{name:p.name},emailRedirectTo:origin,captchaToken:p.captchaToken}});if(error)throw fail('Registration could not be completed. Check your details or contact support.');res.status(201).json({verificationRequired:true,message:'Check your email to verify your account before registering your organization.'});
}));
app.post('/api/auth/login',rateLimit('login',15,900),route(async(req,res)=>{const p=credentials.extend({password:z.string().min(1).max(128)}).parse(req.body);const {data,error}=await authClient().auth.signInWithPassword({email:p.email,password:p.password,options:{captchaToken:p.captchaToken}});if(error||!data.session)throw fail('Unable to sign in. Check your email, password and email verification.',401);saveSession(res,data.session);res.json({success:true});}));
app.post('/api/auth/forgot',rateLimit('recovery',5,900),route(async(req,res)=>{const email=z.string().email().max(254).parse(req.body.email);await authClient().auth.resetPasswordForEmail(email,{redirectTo:origin+'/?reset=1',captchaToken:req.body.captchaToken});res.json({message:'If this account is eligible, a password reset email has been sent.'});}));
app.get('/auth/confirm',route(async(req,res)=>{const type=z.enum(['email','signup','recovery','invite']).parse(req.query.type),token=z.string().min(16).max(200).parse(req.query.token_hash);const {data,error}=await authClient().auth.verifyOtp({type,token_hash:token});if(error||!data.session)return res.redirect('/?auth_error=expired');saveSession(res,data.session);res.redirect(['recovery','invite'].includes(type)?'/?reset=1':'/');}));
// Optional fallback for Supabase's default implicit email templates. Tokens are exchanged for HttpOnly cookies and removed from browser history by the UI.
app.post('/api/auth/session',rateLimit('session',20,900),route(async(req,res)=>{const p=z.object({access_token:z.string().min(20).max(10000),refresh_token:z.string().min(8).max(1000)}).parse(req.body);const {data,error}=await authClient().auth.setSession(p);if(error||!data.user?.email_confirmed_at)throw fail('Invalid confirmation session.',401);saveSession(res,data.session);res.json({success:true});}));
app.use('/api',async(req,res,next)=>{try{
 let token=req.cookies[accessCookie],user;const auth=authClient();let checked=token?await auth.auth.getUser(token):{error:true};
 if(checked.error&&req.cookies[refreshCookie]){const refreshed=await auth.auth.refreshSession({refresh_token:req.cookies[refreshCookie]});if(!refreshed.error){saveSession(res,refreshed.data.session);token=refreshed.data.session.access_token;req.cookies[refreshCookie]=refreshed.data.session.refresh_token;checked={data:{user:refreshed.data.user}};}}
 if(checked.error||!checked.data?.user?.email_confirmed_at)throw fail('Please sign in with a verified account.',401);user=checked.data.user;
 req.actor=user;req.token=token;req.db=userClient(token);req.claims=JSON.parse(Buffer.from(token.split('.')[1],'base64url').toString('utf8'));
 const [profile,membership,platform]=await Promise.all([result(admin.from('profiles').select('*').eq('id',user.id).single()),result(admin.from('memberships').select('*').eq('user_id',user.id).maybeSingle()),result(admin.from('platform_admins').select('user_id').eq('user_id',user.id).maybeSingle())]);req.profile=profile;req.membership=membership;req.platform=!!platform;
 if(membership){req.organization=await result(admin.from('organizations').select('*').eq('id',membership.tenant_id).single());req.subscription=await result(admin.from('saas_subscriptions').select('*').eq('tenant_id',membership.tenant_id).single());req.entitlement=entitlement(req.organization,req.subscription);}
 next();
}catch(error){next(error);}});
function me(req){return {production:true,id:req.actor.id,name:req.profile.name,email:req.actor.email,role:req.membership?.role||null,tenant:req.organization?.name||'',tenantId:req.organization?.id||null,platformAdmin:req.platform,mfaRequired:req.platform&&req.claims.aal!=='aal2',membershipStatus:req.membership?.status||null,organization:req.organization||null,entitlement:req.entitlement||null,needsOnboarding:!req.membership&&!req.platform};}
app.get('/api/auth/me',(req,res)=>res.json(me(req)));
app.get('/api/invitations',route(async(req,res)=>{const invitations=await result(admin.from('saas_invitations').select('id,tenant_id,role,expires_at,organizations(name)').eq('email',req.actor.email.toLowerCase()).eq('status','pending').gt('expires_at',new Date().toISOString()));res.json(invitations);}));
app.post('/api/invitations/accept',route(async(req,res)=>{const invitation_id=z.string().uuid().parse(req.body.invitationId);await rpc('saas_accept_invite',{actor:req.actor.id,invitation_id});res.json({success:true});}));
app.post('/api/auth/logout',route(async(req,res)=>{await admin.auth.admin.signOut(req.token,'global');clearSession(res);res.json({success:true});}));
app.post('/api/auth/password',rateLimit('password',5,900),route(async(req,res)=>{const password=z.string().min(12).max(128).parse(req.body.password);const {error}=await (await mfaClient(req)).auth.updateUser({password});if(error)throw fail('Password could not be updated. Use a fresh recovery link.');res.json({success:true});}));
async function mfaClient(req){const client=authClient();const {error}=await client.auth.setSession({access_token:req.token,refresh_token:req.cookies[refreshCookie]});if(error)throw fail('Sign in again before verifying your authenticator.',401);return client;}
app.get('/api/auth/mfa',route(async(req,res)=>{const client=await mfaClient(req);const {data,error}=await client.auth.mfa.listFactors();if(error)throw fail('Authenticator information unavailable.');res.json({factors:data.totp.map(f=>({id:f.id,status:f.status,name:f.friendly_name}))});}));
app.post('/api/auth/mfa/enroll',rateLimit('mfa-enroll',5,900),route(async(req,res)=>{const client=await mfaClient(req);const {data,error}=await client.auth.mfa.enroll({factorType:'totp',friendlyName:'Gatherhall admin'});if(error)throw fail('Authenticator enrollment failed. Remove unused factors in your Supabase account settings.');res.json({id:data.id,qr:data.totp.qr_code,secret:data.totp.secret});}));
app.post('/api/auth/mfa/verify',rateLimit('mfa-verify',10,900),route(async(req,res)=>{const p=z.object({factorId:z.string().uuid(),code:z.string().regex(/^\d{6}$/)}).parse(req.body),client=await mfaClient(req);const {data,error}=await client.auth.mfa.challengeAndVerify({factorId:p.factorId,code:p.code});if(error)throw fail('Invalid or expired authenticator code.',401);saveSession(res,data);res.json({success:true});}));
const member=(req,res,next)=>{if(!req.membership||req.membership.status!=='active'||req.organization.status!=='active')return next(fail('Organization access is unavailable. Contact your owner or support.',403));next();};
const owner=(req,res,next)=>{if(req.membership?.role!=='owner'||req.membership.status!=='active')return next(fail('Organization owner access required.',403));next();};
const platform=(req,res,next)=>{if(!req.platform||req.claims.aal!=='aal2')return next(fail('Platform administrator access with MFA is required.',403));next();};
installPlatformCMS(app,{admin,result,rpc,route,platform});
installIntegrationSettings(app,{admin,result,route,platform,rateLimit});
installMessaging(app,{admin,result,rpc,route,platform,owner,member,rateLimit,razor});
const writeAccess=(req,res,next)=>{if(!req.entitlement?.active)return next(fail('Your subscription is inactive. You can view records, but must renew before making changes.',402));next();};
app.post('/api/onboarding',rateLimit('onboarding',5,900),route(async(req,res)=>{if(env.REGISTRATION_ENABLED==='false')throw fail('New organization registration is currently closed.',403);if(!billingEnabled)throw fail('Registration opens after billing is configured.',503);const p=z.object({name:z.string().trim().min(2).max(120),phone:z.string().trim().max(30),city:z.string().trim().max(80),planId:z.string().uuid(),interval:z.enum(['monthly','yearly'])}).parse(req.body);const id=await rpc('saas_register_org',{actor:req.actor.id,p});res.status(201).json({tenantId:id});}));
app.get('/api/billing',owner,route(async(req,res)=>{const count=async(kind,active=false)=>{let q=admin.from('saas_records').select('id',{count:'exact',head:true}).eq('tenant_id',req.organization.id).eq('kind',kind);if(active)q=q.eq('body->>status','Active');const {count,error}=await q;if(error)throw fail('Usage unavailable.');return count;};const [halls,staff]=await Promise.all([count('halls'),count('staff',true)]);res.json({organization:req.organization,subscription:req.subscription,entitlement:req.entitlement,usage:{halls,staff},billingEnabled,billingMode,payments:await result(req.db.from('billing_payments').select('*').eq('tenant_id',req.organization.id).order('captured_at',{ascending:false}).limit(50))});}));
app.post('/api/billing/checkout',owner,rateLimit('checkout',10,900),route(async(req,res)=>{
 if(!billingEnabled)throw fail('Billing is not configured yet.',503);
 const s=await rpc('saas_checkout_claim',{actor:req.actor.id,t:req.organization.id});let id=s.provider_subscription_id;
 if(!s.reuse){try{const amount=Number(s.plan_snapshot[s.interval==='yearly'?'yearly_paise':'monthly_paise']);const plan=await razor('plans','POST',{period:s.interval==='yearly'?'yearly':'monthly',interval:1,item:{name:s.plan_snapshot.name+' · '+s.interval+' · v'+s.plan_snapshot.version,amount,currency:'INR',description:'Gatherhall organization subscription'}});const subscription=await razor('subscriptions','POST',{plan_id:plan.id,total_count:s.interval==='yearly'?10:120,quantity:1,customer_notify:1,notes:{tenant_id:req.organization.id,checkout_token:s.checkout_token}});id=subscription.id;await rpc('saas_checkout_finish',{t:req.organization.id,token:s.checkout_token,provider_id:id});}catch(error){await rpc('saas_checkout_finish',{t:req.organization.id,token:s.checkout_token,provider_id:null}).catch(()=>{});throw error;}}
 const provider=await razor('subscriptions/'+encodeURIComponent(id));if(provider.status!=='created')throw fail('A subscription already exists. Refresh its status; do not create a second mandate.',409);
 res.json({key:env.RAZORPAY_KEY_ID,subscription_id:id,name:'Gatherhall',description:s.plan_snapshot.name+' · '+s.interval,prefill:{name:req.profile.name,email:req.actor.email,contact:req.organization.phone},billingMode});
}));
app.post('/api/billing/verify',owner,rateLimit('billing-verify',20,900),route(async(req,res)=>{const p=z.object({razorpay_payment_id:z.string().regex(/^pay_[A-Za-z0-9]+$/),razorpay_subscription_id:z.string().regex(/^sub_[A-Za-z0-9]+$/),razorpay_signature:z.string().length(64)}).parse(req.body);if(p.razorpay_subscription_id!==req.subscription.provider_subscription_id||!billingEnabled||!verifyCheckout(p.razorpay_payment_id,req.subscription.provider_subscription_id,p.razorpay_signature,env.RAZORPAY_KEY_SECRET))throw fail('Payment verification failed.',400);await synchronize(p.razorpay_subscription_id);res.json({verified:true,message:'Mandate verified. Access follows the provider’s current activation status.'});}));
app.post('/api/billing/refresh',owner,rateLimit('billing-refresh',20,900),route(async(req,res)=>{if(req.subscription.provider_subscription_id)await synchronize(req.subscription.provider_subscription_id);res.json({success:true});}));
app.post('/api/billing/cancel',owner,rateLimit('billing-cancel',5,900),route(async(req,res)=>{if(req.body.confirm!=='CANCEL RENEWAL')throw fail('Confirm cancellation explicitly.');const id=req.subscription.provider_subscription_id;if(!id)throw fail('No recurring subscription exists.');if(req.subscription.cancel_at_period_end)return res.json({success:true,message:'Renewal cancellation was already requested.'});await razor('subscriptions/'+encodeURIComponent(id)+'/cancel','POST',{cancel_at_cycle_end:1});const observed=new Date().toISOString();const s=await razor('subscriptions/'+encodeURIComponent(id));await rpc('saas_sync_subscription',{provider_id:id,observed,p:{status:s.status,current_end:s.current_end||0,cancel_at_period_end:true},event_id:null,event_type:'owner.cancel_requested'});res.json({success:true,message:'Renewal cancellation requested. Paid access remains until the verified paid-through date.'});}));
app.get('/api/platform/overview',platform,route(async(_req,res)=>{const [organizations,subscriptions,plans,payments,audit,usage]=await Promise.all([...['organizations','saas_subscriptions','saas_plans','billing_payments','audit_log'].map(table=>result(admin.from(table).select('*').order(table==='audit_log'?'id':'created_at',{ascending:false}).limit(table==='audit_log'?100:1000))),rpc('saas_platform_usage',{actor:_req.actor.id})]);res.json({organizations,subscriptions,usage,plans:plans.map(publicPlan),payments,audit,metrics:billingMetrics(organizations,subscriptions,payments),setup:{database:true,mfa:true,billing:billingEnabled,billingMode,https:secure,email:'Configure custom SMTP and confirmation templates in Supabase',environment:env.NODE_ENV||'development'},limited:organizations.length===1000||subscriptions.length===1000||payments.length===1000});}));
const planSchema=z.object({id:z.string().uuid().optional(),name:z.string().trim().min(1).max(80),description:z.string().trim().max(400),monthly_paise:z.number().int().min(100).max(100000000),yearly_paise:z.number().int().min(100).max(100000000),max_halls:z.number().int().min(1).max(100),max_staff:z.number().int().min(1).max(500),trial_days:z.number().int().min(0).max(30),published:z.boolean()});
app.post('/api/platform/plans',platform,route(async(req,res)=>{const p=planSchema.parse(req.body);if(p.published&&!billingEnabled)throw fail('Configure Razorpay before publishing paid plans.',503);res.json(await rpc('saas_platform_action',{actor:req.actor.id,action:'plan.save',p}));}));
app.post('/api/platform/tenant-status',platform,route(async(req,res)=>{const p=z.object({tenant_id:z.string().uuid(),status:z.enum(['active','suspended']),reason:z.string().trim().min(5).max(500)}).parse(req.body);res.json(await rpc('saas_platform_action',{actor:req.actor.id,action:'tenant.status',p}));}));
app.post('/api/platform/reconcile',platform,rateLimit('reconcile',10,900),route(async(req,res)=>{
 const p=z.object({tenantId:z.string().uuid(),subscriptionId:z.string().regex(/^sub_[A-Za-z0-9]+$/)}).parse(req.body);
 const saved=await result(admin.from('saas_subscriptions').select('*').eq('tenant_id',p.tenantId).single());
 if(!saved.checkout_token||!['creating','uncertain'].includes(saved.checkout_state))throw fail('This checkout does not require reconciliation.',409);
 const subscription=await razor('subscriptions/'+p.subscriptionId),plan=await razor('plans/'+encodeURIComponent(subscription.plan_id));
 if(subscription.notes?.tenant_id!==p.tenantId||subscription.notes?.checkout_token!==saved.checkout_token||Number(subscription.quantity)!==1||plan.period!==(saved.interval==='yearly'?'yearly':'monthly')||Number(plan.interval)!==1||plan.item?.currency!=='INR'||Number(plan.item?.amount)!==Number(saved.plan_snapshot[saved.interval==='yearly'?'yearly_paise':'monthly_paise']))throw fail('Provider subscription does not match the organization checkout lease and agreed plan.',409);
 await rpc('saas_checkout_finish',{t:p.tenantId,token:saved.checkout_token,provider_id:p.subscriptionId});await synchronize(p.subscriptionId);
 await result(admin.from('audit_log').insert({actor_id:req.actor.id,tenant_id:p.tenantId,action:'checkout.reconciled',details:{provider_id:p.subscriptionId}}));res.json({success:true});
}));
app.post('/api/team/invite',owner,member,writeAccess,rateLimit('invite',15,900),route(async(req,res)=>{const rid=z.string().min(1).max(100).parse(req.body.recordId);const invite=await rpc('saas_invite',{actor:req.actor.id,t:req.organization.id,rid});const {error}=await admin.auth.admin.inviteUserByEmail(invite.email,{redirectTo:origin});if(error)throw fail('Invitation is pending but email could not be sent. Check SMTP or whether this account already exists; retry after correction.',502);res.json({success:true,message:'Invitation sent. Access requires verified email and explicit acceptance of this invitation.'});}));

async function loadRecords(req){let rows=[],offset=0;for(;;){const page=await result(req.db.from('saas_records').select('id,kind,body,version').eq('tenant_id',req.membership.tenant_id).order('id').range(offset,offset+999));rows.push(...page);if(page.length<1000)break;offset+=1000;}const records=Object.fromEntries(Object.keys(fields).map(kind=>[kind,rows.filter(r=>r.kind===kind).map(r=>({...r.body,id:r.id,version:r.version}))]));if(['owner','staff'].includes(req.membership.role)){let notes=[],from=0;for(;;){const batch=await result(req.db.from('record_private').select('record_id,operations_notes').eq('tenant_id',req.membership.tenant_id).range(from,from+999));notes.push(...batch);if(batch.length<1000)break;from+=1000;}const byId=new Map(notes.map(n=>[n.record_id,n.operations_notes]));records.bookings=records.bookings.map(b=>({...b,operationsNotes:byId.get(b.id)||''}));}return records;}
app.get('/api/data',member,route(async(req,res)=>res.json(await loadRecords(req))));
app.get('/api/pricing-models',member,route(async(req,res)=>res.json((await loadRecords(req)).plans)));
app.get('/api/pricing-models/:id',member,route(async(req,res)=>{const p=(await loadRecords(req)).plans.find(p=>p.id===req.params.id);if(!p)throw fail('Pricing model not found.',404);res.json(p);}));
app.get('/api/availability',member,route(async(req,res)=>{bookingDuration(req.query);const rows=[];for(let offset=0;;offset+=1000){const batch=await result(admin.from('saas_records').select('id,kind,body').eq('tenant_id',req.membership.tenant_id).in('kind',['halls','bookings']).order('id').range(offset,offset+999));rows.push(...batch);if(batch.length<1000)break;}const visible=await result(req.db.from('saas_records').select('id').eq('tenant_id',req.membership.tenant_id).eq('kind','bookings').eq('id',String(req.query.exclude||'')));const exclude=visible[0]?.id;res.json({date:req.query.date,halls:rows.filter(r=>r.kind==='halls').map(h=>{const maintenance=h.body.status==='Maintenance',conflict=rows.some(b=>b.kind==='bookings'&&b.id!==exclude&&b.body.hallId===h.id&&b.body.status!=='Cancelled'&&bookingsOverlap(b.body,req.query));return {id:h.id,available:!maintenance&&!conflict,reason:maintenance?'Venue is under maintenance':conflict?'Already reserved during this duration':'Available for your celebration'};})});}));
app.get('/api/bookings/:id/confirmation',member,route(async(req,res)=>{const format=z.enum(['full','event']).parse(req.query.format||'full'),records=await loadRecords(req),booking=records.bookings.find(b=>b.id===req.params.id);if(!booking)throw fail('Booking not found.',404);res.set({'Cache-Control':'no-store','Content-Security-Policy':"default-src 'none'; style-src 'unsafe-inline'; script-src 'self'; base-uri 'none'; frame-ancestors 'none'"}).type('html').send(renderConfirmation({booking,client:records.clients.find(c=>c.id===booking.clientId),payments:records.payments.filter(p=>p.bookingId===booking.id),organization:req.organization.name,format}));}));
app.put('/api/settings/profile',route(async(req,res)=>{const p=z.object({name:z.string().trim().min(1).max(120),organization:z.string().trim().min(1).max(120).optional()}).parse(req.body);await rpc('saas_profile_update',{actor:req.actor.id,p});req.profile.name=p.name;if(req.membership?.role==='owner'&&p.organization)req.organization.name=p.organization;res.json(me(req));}));
const resourceAccess=(req,res,next)=>{req.kind=req.params.kind==='pricing-models'?'plans':req.params.kind;if(!fields[req.kind])return next(fail('Resource not found.',404));const role=req.membership.role;if(role==='client'&&(req.kind!=='bookings'||req.method!=='POST'))return next(fail('Team member access required.',403));if(role==='staff'&&['halls','staff','plans','addons'].includes(req.kind))return next(fail('Owner access required.',403));next();};
async function saveRecord(req,res){const id=req.params.id||randomUUID();if(req.body.loginPassword)throw fail('Use secure email invitations from the account screen, not an initial password.');const body=z.record(z.string(),z.unknown()).parse(req.body);const ifMatch=req.get('if-match');const headerDigits=ifMatch==null?'':String(ifMatch).replace(/[^0-9]/g,'');const base=headerDigits===''?(Number.isInteger(body.version)?body.version:null):Number(headerDigits);delete body.version;if(req.kind==='bookings'&&!req.params.id){if(!body.planId)throw fail('Select a pricing model for a new booking.');body.pricingVersion=2;}if(req.kind==='halls'){z.number().int().min(1).max(10000).parse(Number(body.capacity));z.enum(['Available','Maintenance']).parse(body.status);}if(['staff','clients'].includes(req.kind))z.enum(['Active','Inactive']).parse(body.status);const records=await loadRecords(req);if(req.params.id&&!records[req.kind].some(r=>r.id===id))throw fail('Record not found.',404);let data;try{data=validateTenantRecord({kind:req.kind,body,id:req.params.id,tenant:req.membership.tenant_id,role:req.membership.role,records});}catch(error){throw fail(error.message);}const saved=await rpc('saas_save_record',{actor:req.actor.id,t:req.membership.tenant_id,k:req.kind,rid:id,b:data,is_new:!req.params.id,base});if(req.membership.role==='client')delete data.operationsNotes;res.status(req.params.id?200:201).json({...data,id,...(saved&&Number.isInteger(saved.version)?{version:saved.version}:{})});}
app.post('/api/:kind',member,writeAccess,resourceAccess,route(saveRecord));app.put('/api/:kind/:id',member,writeAccess,resourceAccess,route(saveRecord));app.delete('/api/:kind/:id',member,writeAccess,resourceAccess,route(async(req,res)=>{await rpc('saas_delete_record',{actor:req.actor.id,t:req.membership.tenant_id,k:req.kind,rid:req.params.id});res.json({success:true});}));
app.use('/api',(_req,res)=>res.status(404).json({error:'API endpoint not found.'}));
app.use((error,req,res,_next)=>{const status=error instanceof z.ZodError?400:error.status||500;if(status===500)console.error('SaaS request failed',{path:req.path,code:error.code||'internal'});res.status(status).json({error:error instanceof z.ZodError?error.issues[0]?.message||'Check the submitted fields.':status===500?'The request could not be completed. Please try again or contact support.':error.message});});
if(env.NODE_ENV==='production'){app.use(express.static('dist',{index:false}));app.get('*',(_req,res)=>res.sendFile(process.cwd()+'/dist/index.html'));}else{const {createServer}=await import('vite');app.use((await createServer({server:{middlewareMode:true,allowedHosts:true},appType:'spa'})).middlewares);}
const port=Number(env.PORT||3000);if(!Number.isInteger(port)||port<1||port>65535)throw Error('Invalid PORT.');
const stopMessages=startMessageWorker({admin,result,rpc});
const server=app.listen(port,'0.0.0.0',()=>console.log(`Gatherhall SaaS listening on ${port}; billing mode: ${billingEnabled?billingMode:'not configured'}`));
for(const signal of ['SIGTERM','SIGINT'])process.on(signal,()=>{stopMessages();server.close(()=>process.exit(0));setTimeout(()=>process.exit(1),10000).unref();});
